/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelatorioMensalRouteImport } from './routes/relatorio-mensal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioMensalRoute = RelatorioMensalRouteImport.update({
  id: '/relatorio-mensal',
  path: '/relatorio-mensal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/relatorio-mensal': typeof RelatorioMensalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/relatorio-mensal': typeof RelatorioMensalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/relatorio-mensal': typeof RelatorioMensalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/relatorio-mensal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/relatorio-mensal'
  id: '__root__' | '/' | '/relatorio-mensal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RelatorioMensalRoute: typeof RelatorioMensalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-mensal': {
      id: '/relatorio-mensal'
      path: '/relatorio-mensal'
      fullPath: '/relatorio-mensal'
      preLoaderRoute: typeof RelatorioMensalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RelatorioMensalRoute: RelatorioMensalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
