/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecebimentoExternoRouteImport } from './routes/recebimento-externo'
import { Route as RecebimentoInternoRouteImport } from './routes/recebimento-interno'
import { Route as RelatorioMensalRouteImport } from './routes/relatorio-mensal'
import { Route as TreinamentoRouteImport } from './routes/treinamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoExternoRoute = RecebimentoExternoRouteImport.update({
  id: '/recebimento-externo',
  path: '/recebimento-externo',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoInternoRoute = RecebimentoInternoRouteImport.update({
  id: '/recebimento-interno',
  path: '/recebimento-interno',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioMensalRoute = RelatorioMensalRouteImport.update({
  id: '/relatorio-mensal',
  path: '/relatorio-mensal',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentoRoute = TreinamentoRouteImport.update({
  id: '/treinamento',
  path: '/treinamento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recebimento-externo': typeof RecebimentoExternoRoute
  '/recebimento-interno': typeof RecebimentoInternoRoute
  '/relatorio-mensal': typeof RelatorioMensalRoute
  '/treinamento': typeof TreinamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recebimento-externo': typeof RecebimentoExternoRoute
  '/recebimento-interno': typeof RecebimentoInternoRoute
  '/relatorio-mensal': typeof RelatorioMensalRoute
  '/treinamento': typeof TreinamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recebimento-externo': typeof RecebimentoExternoRoute
  '/recebimento-interno': typeof RecebimentoInternoRoute
  '/relatorio-mensal': typeof RelatorioMensalRoute
  '/treinamento': typeof TreinamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recebimento-externo'
    | '/recebimento-interno'
    | '/relatorio-mensal'
    | '/treinamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recebimento-externo'
    | '/recebimento-interno'
    | '/relatorio-mensal'
    | '/treinamento'
  id:
    | '__root__'
    | '/'
    | '/recebimento-externo'
    | '/recebimento-interno'
    | '/relatorio-mensal'
    | '/treinamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecebimentoExternoRoute: typeof RecebimentoExternoRoute
  RecebimentoInternoRoute: typeof RecebimentoInternoRoute
  RelatorioMensalRoute: typeof RelatorioMensalRoute
  TreinamentoRoute: typeof TreinamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento-externo': {
      id: '/recebimento-externo'
      path: '/recebimento-externo'
      fullPath: '/recebimento-externo'
      preLoaderRoute: typeof RecebimentoExternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento-interno': {
      id: '/recebimento-interno'
      path: '/recebimento-interno'
      fullPath: '/recebimento-interno'
      preLoaderRoute: typeof RecebimentoInternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-mensal': {
      id: '/relatorio-mensal'
      path: '/relatorio-mensal'
      fullPath: '/relatorio-mensal'
      preLoaderRoute: typeof RelatorioMensalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamento': {
      id: '/treinamento'
      path: '/treinamento'
      fullPath: '/treinamento'
      preLoaderRoute: typeof TreinamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecebimentoExternoRoute: RecebimentoExternoRoute,
  RecebimentoInternoRoute: RecebimentoInternoRoute,
  RelatorioMensalRoute: RelatorioMensalRoute,
  TreinamentoRoute: TreinamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
